<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rmdata"
    nsURI="http://nexcore.skcc.com/tools/uml/rmdata" nsPrefix="rmd">
  <eClassifiers xsi:type="ecore:EClass" name="RMData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ProjectList" upperBound="-1"
        eType="#//RMObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RequirementList" upperBound="-1"
        eType="#//RMObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="UseCaseList" upperBound="-1"
        eType="#//RMObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RMObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RMObjectId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RMObjectName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ParentId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
